# Docker Compose file for GPDB 6X multinode cluster

version: '3.8'

# The containers
services:
# ==================================================
# The production cluster
# ==================================================
# image: gcr.io/gpdb6-multinode-cluster/gpdb-image
  cdw:
    image: gpdb6-multinode-cluster/gpdb-image
    hostname: cdw
    tty: true
    networks:
      - the-network
    volumes:
      - gpdb5-src-volume:/gpdb5-src
      - gpdb6-src-volume:/gpdb6-src
      - gpupgrade-src-volume:/gpupgrade
      - gpdb-scripts-volume:/gpdb-scripts

  sdw1:
    hostname: sdw1
    image: gpdb6-multinode-cluster/gpdb-image
    tty: true
    networks:
      - the-network
    volumes:
      - gpdb5-src-volume:/gpdb5-src
      - gpdb6-src-volume:/gpdb6-src
      - gpupgrade-src-volume:/gpupgrade
      - gpdb-scripts-volume:/gpdb-scripts

  sdw2:
    hostname: sdw2
    image: gpdb6-multinode-cluster/gpdb-image
    tty: true
    networks:
      - the-network
    volumes:
      - gpdb5-src-volume:/gpdb5-src
      - gpdb6-src-volume:/gpdb6-src
      - gpupgrade-src-volume:/gpupgrade
      - gpdb-scripts-volume:/gpdb-scripts

# The network that bridges all the containers
networks:
  the-network:

# The mounted volumes
volumes:
  gpdb5-src-volume:
    driver_opts:
      o: bind
      type: none
      device: ${GPDB5_SRC}

  gpdb6-src-volume:
    driver_opts:
      o: bind
      type: none
      device: ${GPDB6_SRC}

  gpupgrade-src-volume:
    driver_opts:
      o: bind
      type: none
      device: ${GPUPGRADE_SRC}

  gpdb-scripts-volume:
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/scripts
